name: CI

on:
  push:
    branches:
      - main
jobs: 
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: saludar
        run: echo "Hola, mundo!"
      - name: check node version
        run: node -v
      - name: detected folder
        run: pwd
      - name: list files
        run: ls -la